
name: Build and Release
on:
  push:
jobs:

  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build 
      run: |
        dotnet publish -r win-x64 -c Release --no-self-contained  /p:PublishSingleFile=true /p:DebugType=none /p:DebugSymbols=false
    # Upload : https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: bin\Release\net6.0-windows7.0\win-x64\publish
  release:
    needs: [build]
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release
      - name: Display structure of downloaded files
        run: ls -R
      - name: Compress
        run: |
          zip ToolTray-${GITHUB_REF_NAME}-win-x64.zip *.exe
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          
